import TeacherSideBar from '@/components/layout/teacher/sidebar'
import './globals.css'
import { Inter } from 'next/font/google'
import StudentSideBar from '@/components/layout/student/sidebar'
import AdminSideBar from '@/components/layout/admin/side-bar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="p-4 sm:ml-64">
          <AdminSideBar />
          {children}
        </div>   
      </body>
    </html>
  )
}
